### ISSUE TITLE
Revisit CSRF config once JWT tokens are enabled

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-storage-adapter-java#34]
# Type of issue
- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description
CSRF is disabled for AJAX requests containing a specific header. This is probably not needed once Auth is enabled. It might be useful for development without Auth though. See note in applications.conf.

**Comment by ppathan** [comment]
@dluc Please re-open if not done in TFS
